
# File Generated by machine.

def dataset1_p7_calc_pi_success(n):
    #n = int(n)
    pi = 0
    s = 0
    for i in range(n):    
        if i%2 !=0:        
            if s==0:
                deno = i*1
                s=1
            else:
                deno = i*-1
                s=0
            pi = (pi + 1/deno)
    
    pi = 4 * pi
    print(f"{pi:.10f}")